spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=E-commerce;encrypt=true;trustServerCertificate=true
spring.datasource.username=appuser
spring.datasource.password=App12345!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2
jwt.expiration-ms=86400000

rate-limit.auth.capacity=30
rate-limit.general.capacity=500
