spring.datasource.url=jdbc:sqlserver://NB_SCHAUVINHOLD;databaseName=E-commerce;encrypt=true;trustServerCertificate=true
spring.datasource.username=appuser
spring.datasource.password=App12345!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect