# -------------------------------------------------------
# Perfil Docker MySQL: MySQL corriendo en contenedor local
# Activa este perfil con: SPRING_PROFILES_ACTIVE=docker-mysql
# o desde Maven: ./mvnw spring-boot:run -Dspring-boot.run.profiles=docker-mysql
# -------------------------------------------------------

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:appuser}
spring.datasource.password=${DB_PASS:App12345!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
